---
- name: 'update and upgrade packages.' 
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
- name: Remove Dependencies not required 
  become: yes
  apt:
    autoremove: yes
- name: Install Dependencies
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes